contexts:
  - NATO
  - EAPC
  - GEORGIA
  - KFOR
  - PFP
  - RESOLUTE SUPPORT
  - RUSSIA
  - UKRAINE
  - GLOBAL COALITION
  - CFE
  - ICI
  - INTEROPERABILITY PLATFORM
  - MD
  - NMI
  - NATO RESPONSE FORCE
nations:
  - name: AFG
    full_name: AFG
    classification: U
    nato: false
    eapc: false
    georgia: false
    kfor: false
    pfp: false
    resolute_support: false
    russia: false
    ukraine: false
    global_coalition: true
    cfe: false
    ici: false
    interoperability_platform: false
    md: false
    nmi: false
    response_force: false
  - name: ALB
    full_name: ALB
    classification: CTS
    nato: true
    eapc: false
    georgia: false
    kfor: false
    pfp: false
    resolute_support: false
    russia: false
    ukraine: false
    global_coalition: false
    cfe: false
    ici: false
    interoperability_platform: false
    md: false
    nmi: false
    response_force: false
  - name: ALG
    full_name: ALG
    classification: S
    nato: false
    eapc: false
    georgia: false
    kfor: false
    pfp: false
    resolute_support: false
    russia: false
    ukraine: false
    global_coalition: false
    cfe: false
    ici: false
    interoperability_platform: false
    md: true
    nmi: false
    response_force: false
  - name: ARM
    full_name: ARM
    classification: S
    nato: false
    eapc: true
    georgia: false
    kfor: true
    pfp: true
    resolute_support: true
    russia: false
    ukraine: false
    global_coalition: false
    cfe: true
    ici: false
    interoperability_platform: true
    md: false
    nmi: false
    response_force: false
  - name: AUS
    full_name: AUS
    classification: S
    nato: false
    eapc: false
    georgia: false
    kfor: false
    pfp: false
    resolute_support: true
    russia: false
    ukraine: false
    global_coalition: true
    cfe: false
    ici: false
    interoperability_platform: true
    md: false
    nmi: true
    response_force: false
  - name: AUT
    full_name: AUT
    classification: S
    nato: false
    eapc: true
    georgia: false
    kfor: true
    pfp: true
    resolute_support: true
    russia: false
    ukraine: false
    global_coalition: true
    cfe: false
    ici: false
    interoperability_platform: true
    md: false
    nmi: false
    response_force: false
  - name: AZE
    full_name: AZE
    classification: S
    nato: false
    eapc: true
    georgia: false
    kfor: false
    pfp: true
    resolute_support: true
    russia: false
    ukraine: false
    global_coalition: false
    cfe: true
    ici: false
    interoperability_platform: true
    md: false
    nmi: false
    response_force: false
  - name: BAH
    full_name: BAH
    classification: S
    nato: false
    eapc: false
    georgia: false
    kfor: false
    pfp: false
    resolute_support: false
    russia: false
    ukraine: false
    global_coalition: true
    cfe: false
    ici: true
    interoperability_platform: true
    md: false
    nmi: false
    response_force: false
  - name: BEL
    full_name: BEL
    classification: CTS
    nato: true
    eapc: false
    georgia: false
    kfor: false
    pfp: false
    resolute_support: false
    russia: false
    ukraine: false
    global_coalition: false
    cfe: false
    ici: false
    interoperability_platform: false
    md: false
    nmi: false
    response_force: false
  - name: BGR
    full_name: BGR
    classification: CTS
    nato: true
    eapc: false
    georgia: false
    kfor: false
    pfp: false
    resolute_support: false
    russia: false
    ukraine: false
    global_coalition: false
    cfe: false
    ici: false
    interoperability_platform: false
    md: false
    nmi: false
    response_force: false
  - name: BIH
    full_name: BIH
    classification: S
    nato: false
    eapc: true
    georgia: false
    kfor: false
    pfp: true
    resolute_support: true
    russia: false
    ukraine: false
    global_coalition: true
    cfe: false
    ici: false
    interoperability_platform: true
    md: false
    nmi: false
    response_force: false
  - name: BLR
    full_name: BLR
    classification: U
    nato: false
    eapc: true
    georgia: false
    kfor: false
    pfp: true
    resolute_support: false
    russia: false
    ukraine: false
    global_coalition: false
    cfe: true
    ici: false
    interoperability_platform: false
    md: false
    nmi: false
    response_force: false
  - name: CAN
    full_name: CAN
    classification: CTS
    nato: true
    eapc: false
    georgia: false
    kfor: false
    pfp: false
    resolute_support: false
    russia: false
    ukraine: false
    global_coalition: false
    cfe: false
    ici: false
    interoperability_platform: false
    md: false
    nmi: false
    response_force: false
  - name: CZE
    full_name: CZE
    classification: CTS
    nato: true
    eapc: false
    georgia: false
    kfor: false
    pfp: false
    resolute_support: false
    russia: false
    ukraine: false
    global_coalition: false
    cfe: false
    ici: false
    interoperability_platform: false
    md: false
    nmi: false
    response_force: false
  - name: DEU
    full_name: DEU
    classification: CTS
    nato: true
    eapc: false
    georgia: false
    kfor: false
    pfp: false
    resolute_support: false
    russia: false
    ukraine: false
    global_coalition: false
    cfe: false
    ici: false
    interoperability_platform: false
    md: false
    nmi: false
    response_force: false
  - name: DNK
    full_name: DNK
    classification: CTS
    nato: true
    eapc: false
    georgia: false
    kfor: false
    pfp: false
    resolute_support: false
    russia: false
    ukraine: false
    global_coalition: false
    cfe: false
    ici: false
    interoperability_platform: false
    md: false
    nmi: false
    response_force: false
  - name: EGY
    full_name: EGY
    classification: S
    nato: false
    eapc: false
    georgia: false
    kfor: false
    pfp: false
    resolute_support: false
    russia: false
    ukraine: false
    global_coalition: true
    cfe: false
    ici: false
    interoperability_platform: false
    md: true
    nmi: false
    response_force: false
  - name: ESP
    full_name: ESP
    classification: CTS
    nato: true
    eapc: false
    georgia: false
    kfor: false
    pfp: false
    resolute_support: false
    russia: false
    ukraine: false
    global_coalition: false
    cfe: false
    ici: false
    interoperability_platform: false
    md: false
    nmi: false
    response_force: false
  - name: EST
    full_name: EST
    classification: CTS
    nato: true
    eapc: false
    georgia: false
    kfor: false
    pfp: false
    resolute_support: false
    russia: false
    ukraine: false
    global_coalition: false
    cfe: false
    ici: false
    interoperability_platform: false
    md: false
    nmi: false
    response_force: false
  - name: FIN
    full_name: FIN
    classification: S
    nato: false
    eapc: true
    georgia: false
    kfor: true
    pfp: true
    resolute_support: true
    russia: false
    ukraine: false
    global_coalition: true
    cfe: false
    ici: false
    interoperability_platform: true
    md: false
    nmi: true
    response_force: true
  - name: FRA
    full_name: FRA
    classification: CTS
    nato: true
    eapc: false
    georgia: false
    kfor: false
    pfp: false
    resolute_support: false
    russia: false
    ukraine: false
    global_coalition: false
    cfe: false
    ici: false
    interoperability_platform: false
    md: false
    nmi: false
    response_force: false
  - name: GBR
    full_name: GBR
    classification: CTS
    nato: true
    eapc: false
    georgia: false
    kfor: false
    pfp: false
    resolute_support: false
    russia: false
    ukraine: false
    global_coalition: false
    cfe: false
    ici: false
    interoperability_platform: false
    md: false
    nmi: false
    response_force: false
  - name: GEO
    full_name: GEO
    classification: S
    nato: false
    eapc: true
    georgia: true
    kfor: false
    pfp: true
    resolute_support: true
    russia: false
    ukraine: false
    global_coalition: true
    cfe: true
    ici: false
    interoperability_platform: true
    md: false
    nmi: false
    response_force: true
  - name: GRC
    full_name: GRC
    classification: CTS
    nato: true
    eapc: false
    georgia: false
    kfor: false
    pfp: false
    resolute_support: false
    russia: false
    ukraine: false
    global_coalition: false
    cfe: false
    ici: false
    interoperability_platform: false
    md: false
    nmi: false
    response_force: false
  - name: HRV
    full_name: HRV
    classification: CTS
    nato: true
    eapc: false
    georgia: false
    kfor: false
    pfp: false
    resolute_support: false
    russia: false
    ukraine: false
    global_coalition: false
    cfe: false
    ici: false
    interoperability_platform: false
    md: false
    nmi: false
    response_force: false
  - name: HUN
    full_name: HUN
    classification: CTS
    nato: true
    eapc: false
    georgia: false
    kfor: false
    pfp: false
    resolute_support: false
    russia: false
    ukraine: false
    global_coalition: false
    cfe: false
    ici: false
    interoperability_platform: false
    md: false
    nmi: false
    response_force: false
  - name: IRE
    full_name: IRE
    classification: S
    nato: false
    eapc: true
    georgia: false
    kfor: true
    pfp: true
    resolute_support: false
    russia: false
    ukraine: false
    global_coalition: false
    cfe: false
    ici: false
    interoperability_platform: true
    md: false
    nmi: false
    response_force: false
  - name: IRQ
    full_name: IRQ
    classification: U
    nato: false
    eapc: false
    georgia: false
    kfor: false
    pfp: false
    resolute_support: false
    russia: false
    ukraine: false
    global_coalition: true
    cfe: false
    ici: false
    interoperability_platform: false
    md: false
    nmi: false
    response_force: false
  - name: ISL
    full_name: ISL
    classification: CTS
    nato: true
    eapc: false
    georgia: false
    kfor: false
    pfp: false
    resolute_support: false
    russia: false
    ukraine: false
    global_coalition: false
    cfe: false
    ici: false
    interoperability_platform: false
    md: false
    nmi: false
    response_force: false
  - name: ISR
    full_name: ISR
    classification: S
    nato: false
    eapc: false
    georgia: false
    kfor: false
    pfp: false
    resolute_support: false
    russia: false
    ukraine: false
    global_coalition: false
    cfe: false
    ici: false
    interoperability_platform: false
    md: true
    nmi: false
    response_force: false
  - name: ITA
    full_name: ITA
    classification: CTS
    nato: true
    eapc: false
    georgia: false
    kfor: false
    pfp: false
    resolute_support: false
    russia: false
    ukraine: false
    global_coalition: false
    cfe: false
    ici: false
    interoperability_platform: false
    md: false
    nmi: false
    response_force: false
  - name: JAP
    full_name: JAP
    classification: S
    nato: false
    eapc: false
    georgia: false
    kfor: false
    pfp: false
    resolute_support: false
    russia: false
    ukraine: false
    global_coalition: false
    cfe: false
    ici: false
    interoperability_platform: true
    md: false
    nmi: false
    response_force: false
  - name: LUX
    full_name: LUX
    classification: CTS
    nato: true
    eapc: false
    georgia: false
    kfor: false
    pfp: false
    resolute_support: false
    russia: false
    ukraine: false
    global_coalition: false
    cfe: false
    ici: false
    interoperability_platform: false
    md: false
    nmi: false
    response_force: false
  - name: NLD
    full_name: NLD
    classification: CTS
    nato: true
    eapc: false
    georgia: false
    kfor: false
    pfp: false
    resolute_support: false
    russia: false
    ukraine: false
    global_coalition: false
    cfe: false
    ici: false
    interoperability_platform: false
    md: false
    nmi: false
    response_force: false
  - name: POL
    full_name: POL
    classification: CTS
    nato: true
    eapc: false
    georgia: false
    kfor: false
    pfp: false
    resolute_support: false
    russia: false
    ukraine: false
    global_coalition: false
    cfe: false
    ici: false
    interoperability_platform: false
    md: false
    nmi: false
    response_force: false
  - name: PRT
    full_name: PRT
    classification: CTS
    nato: true
    eapc: false
    georgia: false
    kfor: false
    pfp: false
    resolute_support: false
    russia: false
    ukraine: false
    global_coalition: false
    cfe: false
    ici: false
    interoperability_platform: false
    md: false
    nmi: false
    response_force: false
  - name: USA
    full_name: USA
    classification: CTS
    nato: true
    eapc: false
    georgia: false
    kfor: false
    pfp: false
    resolute_support: false
    russia: false
    ukraine: false
    global_coalition: false
    cfe: false
    ici: false
    interoperability_platform: false
    md: false
    nmi: false
    response_force: false
