// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/services/platform/platform.proto

package platform

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Decision enum
type Decision int32

const (
	Decision_DECISION_UNSPECIFIED Decision = 0
	Decision_DECISION_ALLOW       Decision = 1
	Decision_DECISION_DENY        Decision = 2
	Decision_DECISION_CONDITIONAL Decision = 3
)

// Enum value maps for Decision.
var (
	Decision_name = map[int32]string{
		0: "DECISION_UNSPECIFIED",
		1: "DECISION_ALLOW",
		2: "DECISION_DENY",
		3: "DECISION_CONDITIONAL",
	}
	Decision_value = map[string]int32{
		"DECISION_UNSPECIFIED": 0,
		"DECISION_ALLOW":       1,
		"DECISION_DENY":        2,
		"DECISION_CONDITIONAL": 3,
	}
)

func (x Decision) Enum() *Decision {
	p := new(Decision)
	*p = x
	return p
}

func (x Decision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Decision) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_services_platform_platform_proto_enumTypes[0].Descriptor()
}

func (Decision) Type() protoreflect.EnumType {
	return &file_proto_services_platform_platform_proto_enumTypes[0]
}

func (x Decision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Decision.Descriptor instead.
func (Decision) EnumDescriptor() ([]byte, []int) {
	return file_proto_services_platform_platform_proto_rawDescGZIP(), []int{0}
}

// Request message for GetDecision
type GetDecisionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Subject making the request (e.g., user ID, service ID)
	SubjectAttributes map[string]*structpb.Value `protobuf:"bytes,1,rep,name=subject_attributes,json=subjectAttributes,proto3" json:"subject_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Resource being accessed
	ResourceAttributes map[string]string `protobuf:"bytes,2,rep,name=resource_attributes,json=resourceAttributes,proto3" json:"resource_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Action being performed
	Action string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	// Additional context for the decision
	Context map[string]string `protobuf:"bytes,4,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optional policy ID to evaluate against
	PolicyId      string `protobuf:"bytes,5,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDecisionRequest) Reset() {
	*x = GetDecisionRequest{}
	mi := &file_proto_services_platform_platform_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDecisionRequest) ProtoMessage() {}

func (x *GetDecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_platform_platform_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDecisionRequest.ProtoReflect.Descriptor instead.
func (*GetDecisionRequest) Descriptor() ([]byte, []int) {
	return file_proto_services_platform_platform_proto_rawDescGZIP(), []int{0}
}

func (x *GetDecisionRequest) GetSubjectAttributes() map[string]*structpb.Value {
	if x != nil {
		return x.SubjectAttributes
	}
	return nil
}

func (x *GetDecisionRequest) GetResourceAttributes() map[string]string {
	if x != nil {
		return x.ResourceAttributes
	}
	return nil
}

func (x *GetDecisionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *GetDecisionRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetDecisionRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

// Response message for GetDecision
type GetDecisionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Decision result
	Decision Decision `protobuf:"varint,1,opt,name=decision,proto3,enum=platform.Decision" json:"decision,omitempty"`
	// Reason for the decision
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// Additional details about the decision
	Details map[string]string `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Timestamp when the decision was made
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Policy that was evaluated
	EvaluatedPolicy string `protobuf:"bytes,5,opt,name=evaluated_policy,json=evaluatedPolicy,proto3" json:"evaluated_policy,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetDecisionResponse) Reset() {
	*x = GetDecisionResponse{}
	mi := &file_proto_services_platform_platform_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDecisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDecisionResponse) ProtoMessage() {}

func (x *GetDecisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_platform_platform_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDecisionResponse.ProtoReflect.Descriptor instead.
func (*GetDecisionResponse) Descriptor() ([]byte, []int) {
	return file_proto_services_platform_platform_proto_rawDescGZIP(), []int{1}
}

func (x *GetDecisionResponse) GetDecision() Decision {
	if x != nil {
		return x.Decision
	}
	return Decision_DECISION_UNSPECIFIED
}

func (x *GetDecisionResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *GetDecisionResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *GetDecisionResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *GetDecisionResponse) GetEvaluatedPolicy() string {
	if x != nil {
		return x.EvaluatedPolicy
	}
	return ""
}

// Request message for GetEntitlements
type GetEntitlementsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Subject to get entitlements for
	Subject map[string]*structpb.Value `protobuf:"bytes,1,rep,name=subject,proto3" json:"subject,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optional resource filter
	ResourceFilter string `protobuf:"bytes,2,opt,name=resource_filter,json=resourceFilter,proto3" json:"resource_filter,omitempty"`
	// Optional action filter
	ActionFilter string `protobuf:"bytes,3,opt,name=action_filter,json=actionFilter,proto3" json:"action_filter,omitempty"`
	// Optional context for entitlement evaluation
	Context map[string]string `protobuf:"bytes,4,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Pagination token
	PageToken string `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Page size (default: 50, max: 1000)
	PageSize      int32 `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntitlementsRequest) Reset() {
	*x = GetEntitlementsRequest{}
	mi := &file_proto_services_platform_platform_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntitlementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntitlementsRequest) ProtoMessage() {}

func (x *GetEntitlementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_platform_platform_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntitlementsRequest.ProtoReflect.Descriptor instead.
func (*GetEntitlementsRequest) Descriptor() ([]byte, []int) {
	return file_proto_services_platform_platform_proto_rawDescGZIP(), []int{2}
}

func (x *GetEntitlementsRequest) GetSubject() map[string]*structpb.Value {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *GetEntitlementsRequest) GetResourceFilter() string {
	if x != nil {
		return x.ResourceFilter
	}
	return ""
}

func (x *GetEntitlementsRequest) GetActionFilter() string {
	if x != nil {
		return x.ActionFilter
	}
	return ""
}

func (x *GetEntitlementsRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetEntitlementsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *GetEntitlementsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Response message for GetEntitlements
type GetEntitlementsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of entitlements
	Entitlements []*Entitlement `protobuf:"bytes,1,rep,name=entitlements,proto3" json:"entitlements,omitempty"`
	// Next page token (empty if no more pages)
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// Total count of entitlements (optional)
	TotalCount int64 `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	// Timestamp when entitlements were retrieved
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntitlementsResponse) Reset() {
	*x = GetEntitlementsResponse{}
	mi := &file_proto_services_platform_platform_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntitlementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntitlementsResponse) ProtoMessage() {}

func (x *GetEntitlementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_platform_platform_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntitlementsResponse.ProtoReflect.Descriptor instead.
func (*GetEntitlementsResponse) Descriptor() ([]byte, []int) {
	return file_proto_services_platform_platform_proto_rawDescGZIP(), []int{3}
}

func (x *GetEntitlementsResponse) GetEntitlements() []*Entitlement {
	if x != nil {
		return x.Entitlements
	}
	return nil
}

func (x *GetEntitlementsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *GetEntitlementsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetEntitlementsResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Entitlement represents a permission or access right
type Entitlement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the entitlement
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Subject the entitlement applies to
	Subject string `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	// Resource the entitlement grants access to
	Resource string `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	// Actions allowed on the resource
	Actions []string `protobuf:"bytes,4,rep,name=actions,proto3" json:"actions,omitempty"`
	// Conditions that must be met for the entitlement to be valid
	Conditions []*Condition `protobuf:"bytes,5,rep,name=conditions,proto3" json:"conditions,omitempty"`
	// Entitlement metadata
	Metadata map[string]string `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// When the entitlement was created
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// When the entitlement expires (optional)
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Whether the entitlement is active
	Active        bool `protobuf:"varint,9,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entitlement) Reset() {
	*x = Entitlement{}
	mi := &file_proto_services_platform_platform_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entitlement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entitlement) ProtoMessage() {}

func (x *Entitlement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_platform_platform_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entitlement.ProtoReflect.Descriptor instead.
func (*Entitlement) Descriptor() ([]byte, []int) {
	return file_proto_services_platform_platform_proto_rawDescGZIP(), []int{4}
}

func (x *Entitlement) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entitlement) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Entitlement) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *Entitlement) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *Entitlement) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *Entitlement) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Entitlement) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Entitlement) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Entitlement) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

// Condition represents a condition that must be met
type Condition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of condition (e.g., "time", "location", "attribute")
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Operator for the condition (e.g., "equals", "contains", "greater_than")
	Operator string `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	// Value to compare against
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// Additional parameters for the condition
	Parameters    map[string]string `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_proto_services_platform_platform_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_platform_platform_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_proto_services_platform_platform_proto_rawDescGZIP(), []int{5}
}

func (x *Condition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Condition) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *Condition) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Condition) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

var File_proto_services_platform_platform_proto protoreflect.FileDescriptor

const file_proto_services_platform_platform_proto_rawDesc = "" +
	"\n" +
	"&proto/services/platform/platform.proto\x12\bplatform\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xba\x04\n" +
	"\x12GetDecisionRequest\x12b\n" +
	"\x12subject_attributes\x18\x01 \x03(\v23.platform.GetDecisionRequest.SubjectAttributesEntryR\x11subjectAttributes\x12e\n" +
	"\x13resource_attributes\x18\x02 \x03(\v24.platform.GetDecisionRequest.ResourceAttributesEntryR\x12resourceAttributes\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12C\n" +
	"\acontext\x18\x04 \x03(\v2).platform.GetDecisionRequest.ContextEntryR\acontext\x12\x1b\n" +
	"\tpolicy_id\x18\x05 \x01(\tR\bpolicyId\x1a\\\n" +
	"\x16SubjectAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\x1aE\n" +
	"\x17ResourceAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc4\x02\n" +
	"\x13GetDecisionResponse\x12.\n" +
	"\bdecision\x18\x01 \x01(\x0e2\x12.platform.DecisionR\bdecision\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12D\n" +
	"\adetails\x18\x03 \x03(\v2*.platform.GetDecisionResponse.DetailsEntryR\adetails\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12)\n" +
	"\x10evaluated_policy\x18\x05 \x01(\tR\x0fevaluatedPolicy\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc4\x03\n" +
	"\x16GetEntitlementsRequest\x12G\n" +
	"\asubject\x18\x01 \x03(\v2-.platform.GetEntitlementsRequest.SubjectEntryR\asubject\x12'\n" +
	"\x0fresource_filter\x18\x02 \x01(\tR\x0eresourceFilter\x12#\n" +
	"\raction_filter\x18\x03 \x01(\tR\factionFilter\x12G\n" +
	"\acontext\x18\x04 \x03(\v2-.platform.GetEntitlementsRequest.ContextEntryR\acontext\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\x1aR\n" +
	"\fSubjectEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd7\x01\n" +
	"\x17GetEntitlementsResponse\x129\n" +
	"\fentitlements\x18\x01 \x03(\v2\x15.platform.EntitlementR\fentitlements\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x03R\n" +
	"totalCount\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xae\x03\n" +
	"\vEntitlement\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\tR\bresource\x12\x18\n" +
	"\aactions\x18\x04 \x03(\tR\aactions\x123\n" +
	"\n" +
	"conditions\x18\x05 \x03(\v2\x13.platform.ConditionR\n" +
	"conditions\x12?\n" +
	"\bmetadata\x18\x06 \x03(\v2#.platform.Entitlement.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x16\n" +
	"\x06active\x18\t \x01(\bR\x06active\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd5\x01\n" +
	"\tCondition\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\boperator\x18\x02 \x01(\tR\boperator\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12C\n" +
	"\n" +
	"parameters\x18\x04 \x03(\v2#.platform.Condition.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*e\n" +
	"\bDecision\x12\x18\n" +
	"\x14DECISION_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eDECISION_ALLOW\x10\x01\x12\x11\n" +
	"\rDECISION_DENY\x10\x02\x12\x18\n" +
	"\x14DECISION_CONDITIONAL\x10\x032\xb5\x01\n" +
	"\x0fPlatformService\x12J\n" +
	"\vGetDecision\x12\x1c.platform.GetDecisionRequest\x1a\x1d.platform.GetDecisionResponse\x12V\n" +
	"\x0fGetEntitlements\x12 .platform.GetEntitlementsRequest\x1a!.platform.GetEntitlementsResponseB\x1cZ\x1astratium/services/platformb\x06proto3"

var (
	file_proto_services_platform_platform_proto_rawDescOnce sync.Once
	file_proto_services_platform_platform_proto_rawDescData []byte
)

func file_proto_services_platform_platform_proto_rawDescGZIP() []byte {
	file_proto_services_platform_platform_proto_rawDescOnce.Do(func() {
		file_proto_services_platform_platform_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_services_platform_platform_proto_rawDesc), len(file_proto_services_platform_platform_proto_rawDesc)))
	})
	return file_proto_services_platform_platform_proto_rawDescData
}

var file_proto_services_platform_platform_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_services_platform_platform_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_services_platform_platform_proto_goTypes = []any{
	(Decision)(0),                   // 0: platform.Decision
	(*GetDecisionRequest)(nil),      // 1: platform.GetDecisionRequest
	(*GetDecisionResponse)(nil),     // 2: platform.GetDecisionResponse
	(*GetEntitlementsRequest)(nil),  // 3: platform.GetEntitlementsRequest
	(*GetEntitlementsResponse)(nil), // 4: platform.GetEntitlementsResponse
	(*Entitlement)(nil),             // 5: platform.Entitlement
	(*Condition)(nil),               // 6: platform.Condition
	nil,                             // 7: platform.GetDecisionRequest.SubjectAttributesEntry
	nil,                             // 8: platform.GetDecisionRequest.ResourceAttributesEntry
	nil,                             // 9: platform.GetDecisionRequest.ContextEntry
	nil,                             // 10: platform.GetDecisionResponse.DetailsEntry
	nil,                             // 11: platform.GetEntitlementsRequest.SubjectEntry
	nil,                             // 12: platform.GetEntitlementsRequest.ContextEntry
	nil,                             // 13: platform.Entitlement.MetadataEntry
	nil,                             // 14: platform.Condition.ParametersEntry
	(*timestamppb.Timestamp)(nil),   // 15: google.protobuf.Timestamp
	(*structpb.Value)(nil),          // 16: google.protobuf.Value
}
var file_proto_services_platform_platform_proto_depIdxs = []int32{
	7,  // 0: platform.GetDecisionRequest.subject_attributes:type_name -> platform.GetDecisionRequest.SubjectAttributesEntry
	8,  // 1: platform.GetDecisionRequest.resource_attributes:type_name -> platform.GetDecisionRequest.ResourceAttributesEntry
	9,  // 2: platform.GetDecisionRequest.context:type_name -> platform.GetDecisionRequest.ContextEntry
	0,  // 3: platform.GetDecisionResponse.decision:type_name -> platform.Decision
	10, // 4: platform.GetDecisionResponse.details:type_name -> platform.GetDecisionResponse.DetailsEntry
	15, // 5: platform.GetDecisionResponse.timestamp:type_name -> google.protobuf.Timestamp
	11, // 6: platform.GetEntitlementsRequest.subject:type_name -> platform.GetEntitlementsRequest.SubjectEntry
	12, // 7: platform.GetEntitlementsRequest.context:type_name -> platform.GetEntitlementsRequest.ContextEntry
	5,  // 8: platform.GetEntitlementsResponse.entitlements:type_name -> platform.Entitlement
	15, // 9: platform.GetEntitlementsResponse.timestamp:type_name -> google.protobuf.Timestamp
	6,  // 10: platform.Entitlement.conditions:type_name -> platform.Condition
	13, // 11: platform.Entitlement.metadata:type_name -> platform.Entitlement.MetadataEntry
	15, // 12: platform.Entitlement.created_at:type_name -> google.protobuf.Timestamp
	15, // 13: platform.Entitlement.expires_at:type_name -> google.protobuf.Timestamp
	14, // 14: platform.Condition.parameters:type_name -> platform.Condition.ParametersEntry
	16, // 15: platform.GetDecisionRequest.SubjectAttributesEntry.value:type_name -> google.protobuf.Value
	16, // 16: platform.GetEntitlementsRequest.SubjectEntry.value:type_name -> google.protobuf.Value
	1,  // 17: platform.PlatformService.GetDecision:input_type -> platform.GetDecisionRequest
	3,  // 18: platform.PlatformService.GetEntitlements:input_type -> platform.GetEntitlementsRequest
	2,  // 19: platform.PlatformService.GetDecision:output_type -> platform.GetDecisionResponse
	4,  // 20: platform.PlatformService.GetEntitlements:output_type -> platform.GetEntitlementsResponse
	19, // [19:21] is the sub-list for method output_type
	17, // [17:19] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_proto_services_platform_platform_proto_init() }
func file_proto_services_platform_platform_proto_init() {
	if File_proto_services_platform_platform_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_services_platform_platform_proto_rawDesc), len(file_proto_services_platform_platform_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_services_platform_platform_proto_goTypes,
		DependencyIndexes: file_proto_services_platform_platform_proto_depIdxs,
		EnumInfos:         file_proto_services_platform_platform_proto_enumTypes,
		MessageInfos:      file_proto_services_platform_platform_proto_msgTypes,
	}.Build()
	File_proto_services_platform_platform_proto = out.File
	file_proto_services_platform_platform_proto_goTypes = nil
	file_proto_services_platform_platform_proto_depIdxs = nil
}
